//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Xamarin.Essentials;

    public partial class empleado
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        [EmailAddress]
        [Required(ErrorMessage = "Correo es obligatorio")]
        public string Email { get; set; }
        public string Departamento { get; set; }
        public string Cargo { get; set; }
        public Nullable<System.DateTime> Fecha_ingreso { get; set; }
        public Nullable<int> Salario { get; set; }
    }
}
